# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23d458cfb23b240e436d8063d91c20266850b069cc7446bf0d15e1c754af7a343e5e5f24798f29fc11f6b17a85dda00f4dfeb60758f68a4688601d1780d36b6d

test:
  secret_key_base: 08b4e72c898d6c2686a88af97169a54aba3ff88563c5a90b1028861f3031b9c119fb934d4e4708caf2c4e17cf37a498407136d6d52acdc3d3bd9cddfe88e145a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
